package com.ftl.learning.jaxws.service.wsclient;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.4-b01 Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "testService", targetNamespace = "http://service.jaxws.learning.ftl.com/", wsdlLocation = "http://localhost:9080/business_server/testService?wsdl")
public class TestService_Service extends Service {

	private final static URL TESTSERVICE_WSDL_LOCATION;
	private final static WebServiceException TESTSERVICE_EXCEPTION;
	private final static QName TESTSERVICE_QNAME = new QName("http://service.jaxws.learning.ftl.com/", "testService");

	static {
		URL url = null;
		WebServiceException e = null;
		try {
			url = new URL("http://localhost:9080/business_server/testService?wsdl");
		} catch (MalformedURLException ex) {
			e = new WebServiceException(ex);
		}
		TESTSERVICE_WSDL_LOCATION = url;
		TESTSERVICE_EXCEPTION = e;
	}

	public TestService_Service() {
		super(__getWsdlLocation(), TESTSERVICE_QNAME);
	}

	public TestService_Service(URL wsdlLocation) {
		super(wsdlLocation, TESTSERVICE_QNAME);
	}

	public TestService_Service(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	/**
	 * 
	 * @return returns TestService
	 */
	@WebEndpoint(name = "testServicePort")
	public TestService getTestServicePort() {
		return super.getPort(new QName("http://service.jaxws.learning.ftl.com/", "testServicePort"), TestService.class);
	}

	/**
	 * 
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy. Supported features not in the
	 *            <code>features</code> parameter will have their default values.
	 * @return returns TestService
	 */
	@WebEndpoint(name = "testServicePort")
	public TestService getTestServicePort(WebServiceFeature... features) {
		return super.getPort(new QName("http://service.jaxws.learning.ftl.com/", "testServicePort"), TestService.class, features);
	}

	private static URL __getWsdlLocation() {
		if (TESTSERVICE_EXCEPTION != null) {
			throw TESTSERVICE_EXCEPTION;
		}
		return TESTSERVICE_WSDL_LOCATION;
	}

}
